### ISSUE TITLE
Live preview is broken on Ruby 2.3.3+

### ISSUE THREAD

**Issue by raul** [heroku/devcenter-cli#24]
```
/Users/ryan.cross/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/devcenter-1.1.8/lib/devcenter/previewer/file_listener.rb:10:in `initialize': undefined method `filter' for #<Listen::Listener:0x007fbb741fb8a0> (NoMethodError)
```

It works on Ruby 2.2.4 and both versions install Listen 1.3.1.
